### ISSUE TITLE
19b

### ISSUE THREAD

**Issue by kolboch** [wojteko22/oracle#2]
getting rid of (null) in result:

**SELECT "Imie", 
       "Funkcja", 
       DECODE("Szef 1", NULL, ' ', "Szef 1") "Szef 1",
       DECODE("Szef 2", NULL, ' ', "Szef 2") "Szef 2",
       DECODE("Szef 3", NULL, ' ', "Szef 3") "Szef 3"**
FROM (
    SELECT
      IMIE "Imie szefa",
      LEVEL "Poziom szefa",
      CONNECT_BY_ROOT IMIE "Imie",
      CONNECT_BY_ROOT FUNKCJA "Funkcja"
    FROM KOCURY
    WHERE CONNECT_BY_ROOT PSEUDO <> PSEUDO
    CONNECT BY PRIOR SZEF = PSEUDO
    START WITH FUNKCJA IN ('MILUSIA', 'KOT'))
PIVOT (
  MAX("Imie szefa")
  FOR ("Poziom szefa")
  IN (  '2' "Szef 1",
        '3' "Szef 2",
        '4' "Szef 3")
);

**Comment by wojteko22** [comment]
Thanks, I have corrected that. If it would not be a problem, make a pull request in the future, please, it would be easier for me ;)
